### PR TITLE
Don't download additional dependencies if you are a submodule

### PR DESCRIPTION
**Pull request by haenkel**
This should have been part of #13 but I forgot to add it there.

### CODE REVIEW

**Comment by baconpaul** [comment]
Ahh great. Do you have merge on these repos? If not I'l give it to you.

**Comment by haenkel** [comment]
i don't

**Comment by baconpaul** [comment]
ok just sent you invites to all of em. 

Just ask if you need it to any others and i've forgotten!

**Comment by haenkel** [comment]
thanks!

**Pull request merged**
